[tool.briefcase]
project_name = "Wordle Clone"
bundle = "cs150.decastro.hansgabriel"
version = "0.0.1"
url = "https://hansgabriel.decastro.cs150/wordleclone"
license = "BSD license"
author = 'Hans Gabriel H. De Castro'
author_email = "hhdecastro@up.edu.ph"

[tool.briefcase.app.wordleclone]
formal_name = "Wordle Clone"
description = "Wordle clone using BeeWare"
icon = "src/wordleclone/resources/wordleclone"
sources = ['src/wordleclone']
requires = ['src/wordle-allowed-guesses.txt','src/wordle-answers-alphabetical.txt']


[tool.briefcase.app.wordleclone.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.wordleclone.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.wordleclone.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.wordleclone.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.wordleclone.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
